window.onload=function(){
	var projectObject=[
		{
			"link":"https://luuman.github.io/FrontEndGuide/V1/index.html#page_9",
			"linkName":"前端导航"
		},
		{
			"link":"http://www.haorooms.com/nav",
			"linkName":"前端技术导航"
		},
		{
			"link":"http://www.alloyteam.com/nav/",
			"linkName":"腾讯前端技术导航"
		},
		{
			"link":"https://docs.pfan123.com/",
			"linkName":"前端导航平台"
		},
		{
			"link":"https://segmentfault.com/a/1190000010686636",
			"linkName":"前端学习资源"
		},
		{
			"link":"https://segmentfault.com/a/1190000003510001",
			"linkName":"github资源收集"
		},
		{
			"link":"http://www.daqianduan.com/nav",
			"linkName":"大前端网址导航"
		},
		{
			"link":"http://caibaojian.com/c/qianduan",
			"linkName":"前端大神俱乐部"
		},
		{
			"link":"http://123.jser.us/",
			"linkName":"前端导航站"
		},
		{
			"link":"http://caibaojian.com/links",
			"linkName":"前端开发博客集合"
		},
		{
			"link":"http://collect.w3ctrain.com/",
			"linkName":"前端收藏夹"
		},
		{
			"link":"http://jsdig.com/",
			"linkName":"前端导航网"
		},
		{
			"link":"https://123.w3cschool.cn/plk2fi",
			"linkName":"前端学习资源汇总"
		},
		{
			"link":"http://so.uigreat.com/",
			"linkName":"UI设计师导航"
		},
		{
			"link":"http://www.cnblogs.com/chenyablog/p/5551143.html",
			"linkName":"常用技术网站整理"
		},
		{
			"link":"http://f2er.club/",
			"linkName":"前端人的俱乐部"
		},
		{
			"link":"https://github.com/nieweidong/fetool",
			"linkName":"大前端工具集"
		},
		{
			"link":"https://github.com/foru17/front-end-collect",
			"linkName":"前端收集箱"
		},
		{
			"link":"https://www.awesomes.cn/",
			"linkName":"前端资源库"
		}
	];
	
	new Vue({
		el:'#resourceUl',
		data:{
			items:projectObject
		}
	});
}
